0
1
2
3
varibad miniworld
4
Traceback (most recent call last):
  File "main_varibad.py", line 199, in <module>
    main()
  File "main_varibad.py", line 48, in main
    raise ValueError("Experiment already exists at: {}".format(exp_dir))
ValueError: Experiment already exists at: experiments/miniworld_sign/varibad
